### ISSUE TITLE
Tag "Forth"

### ISSUE THREAD

**Issue by FForth** [tiluser/Creole-Forth#2]
Please create a "forth" tag and ... for this project. (Label "Manage topic" in open project)

**Comment by tiluser** [comment]
Hi, I had created three tags for all the Forth DSLs I have in "Manage Topic"
1. Creole Forth for Lazarus/Delphi
2. Creole Forth for Excel
3. Creole Forth for JavaScript
4. Creole Forth for Python
5. Creole Forth for C#
